[workspace]
resolver = "2"
members = [
    "mylang-core",
    "mylang-cli",
    "mylang-wasm-codegen",
    "mylang-llvm-codegen",
    "mylang-playground",
    "mylang-lsp",
]

[workspace.dependencies]
thiserror = { version = "2.0", default-features = false }
