[workspace]
resolver = "2"
members = [
    "mylang-core",
    "mylang-cli", "mylang-wasm-codegen", "mylang-llvm-codegen",
]

[workspace.dependencies]
thiserror = { version = "2.0", default-features = false }
